version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.14.0}
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elastic
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./volumes/elastic/data:/usr/share/elasticsearch/data"
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logback.conf
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logback.conf:/etc/logstash/conf.d/logback.conf
      - ./docker-logs/logstash:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      CLUSTER_NAME: es-cluster
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

volumes:
  es_data:
    driver: local
