version: '3.8'

services:

  config-server:
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    container_name: config-server
    ports:
      - "5007:5007"
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server"
      - "SERVER_PORT=8888"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  config-server-ha:
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    container_name: config-server-ha
    ports:
      - "5018:5018"
      - "8889:8889"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5018 -Xms128m -Xmx256m"
      - "LOG_APP-NAME=config-server-ha"
      - "SERVER_PORT=8889"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  source-to-kafka-service:
    image: ${GROUP_ID}/source.to.kafka.service:${SERVICE_VERSION:-latest}
    container_name: source-to-kafka-service
    ports:
      - "5005:5005"
    entrypoint: [ "check-config-server-started.sh" ]
    user: root
    volumes:
      - "./docker-logs:/workspace/source-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    depends_on:
      - config-server
      - kafka
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAMES-TO-CREATE_0=source-topic"
      - "KAFKA-CONFIG_TOPIC-NAMES-TO-CREATE_1=source-analytics-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "LOG_APP-NAME=source-to-kafka-service"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
      - "SPRING_ZIPKIN_SENDER_TYPE=web"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "SOURCE_BEARER_TOKEN=${SOURCE_BEARER_TOKEN}"
    networks:
      - ${GLOBAL_NETWORK:-services}

  kafka-to-elastic-service:
    image: ${GROUP_ID}/kafka.to.elastic.service:${SERVICE_VERSION:-latest}
    container_name: kafka-to-elastic-service
    ports:
      - "5006:5006"
    entrypoint: [ "check-kafka-topics-created.sh" ]
    user: root
    volumes:
      - "./docker-logs:/workspace/kafka-to-elastic-service/logs"
      - "./check-kafka-topics-created.sh:/usr/local/bin/check-kafka-topics-created.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    depends_on:
      - config-server
      - source-to-kafka-service
      - kafka
      - elasticsearch
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=error"
      - "LOGGING_LEVEL_ROOT=error"
      - "KAFKA-CONFIG_TOPIC-NAME=source-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "ELASTIC-CONFIG_INDEX-NAME=source-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=elasticsearch:9200"
      - "LOG_APP-NAME=kafka-to-elastic-service"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=elasticsearch:9200"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  elastic-query-service-1:
    image: ${GROUP_ID}/elastic.query.service:${SERVICE_VERSION:-latest}
    container_name: elastic-query-service-1
    ports:
      - "5008:5008"
      - "8183:8183"
    entrypoint: [ "check-config-server-started.sh" ]
    user: root
    volumes:
      - "./docker-logs:/workspace/elastic-query-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    depends_on:
      - config-server
      - kafka-to-elastic-service
      - elasticsearch
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "ELASTIC-CONFIG_INDEX-NAME=source-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=elasticsearch:9200"
      - "SERVER_PORT=8183"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/certs"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/token"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true"
      - "ELASTIC-QUERY-SERVICE_QUERY-FROM-KAFKA-STATE-STORE_URI=http://gateway-service/kafka-streams-service/get-word-count-by-word/{word}"
      - "ELASTIC-QUERY-SERVICE_QUERY-FROM-ANALYTICS-DATABASE_URI=http://gateway-service/analytics-service/get-word-count-by-word/{word}"
      - "ELASTIC-QUERY-SERVICE_WEBCLIENT_QUERY-TYPE=ANALYTICS_DATABASE"
      - "LOG_APP-NAME=elastic-query-service-1"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=elasticsearch:9200"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  elastic-query-service-2:
    image: ${GROUP_ID}/elastic.query.service:${SERVICE_VERSION:-latest}
    container_name: elastic-query-service-2
    ports:
      - "5009:5009"
      - "8186:8186"
    entrypoint: [ "check-config-server-started.sh" ]
    user: root
    volumes:
      - "./docker-logs:/workspace/elastic-query-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    depends_on:
      - config-server
      - kafka-to-elastic-service
      - elasticsearch
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "ELASTIC-CONFIG_INDEX-NAME=source-index"
      - "ELASTIC-CONFIG_CONNECTION-URL=elasticsearch:9200"
      - "SERVER_PORT=8186"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/certs"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/token"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true"
      - "SPRING_DATASOURCE_INITIALIZATION-MODE=never"
      - "ELASTIC-QUERY-SERVICE_QUERY-FROM-KAFKA-STATE-STORE_URI=http://gateway-service/kafka-streams-service/get-word-count-by-word/{word}"
      - "ELASTIC-QUERY-SERVICE_QUERY-FROM-ANALYTICS-DATABASE_URI=http://gateway-service/analytics-service/get-word-count-by-word/{word}"
      - "ELASTIC-QUERY-SERVICE_WEBCLIENT_QUERY-TYPE=ANALYTICS_DATABASE"
      - "LOG_APPNAME=elastic-query-service-2"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=elastic-1:9200"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  elastic-query-web-client:
    image: ${GROUP_ID}/elastic.query.web.client:${SERVICE_VERSION:-latest}
    container_name: elastic-query-web-client
    ports:
      - "5010:5010"
      - "8184:8184"
    volumes:
      - "./docker-logs:/workspace/elastic-query-web-client/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8184"
      - "SERVER_SERVLET_CONTEXT-PATH=/elastic-query-web-client"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_BASE-URL=http://gateway-service/elastic-query-service/documents"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_ID=elastic-query-service-1"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_HOST=elastic-query-service-1"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_0_PORT=8183"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_ID=elastic-query-service-2"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_HOST=elastic-query-service-2"
      - "ELASTIC-QUERY-WEB-CLIENT_WEB-CLIENT_INSTANCES_1_PORT=8186"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm"
      - "SECURITY_LOGOUT-SUCCESS-URL=http://elastic-query-web-client:8184/elastic-query-web-client"
      - "SECURITY_DEFAULT-CLIENT-REGISTRATION-ID=keycloak"
      - "LOG_APP-NAME=elastic-query-web-client"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  kafka-streams-service:
    image: ${GROUP_ID}/kafka.streams.service:${SERVICE_VERSION:-latest}
    container_name: kafka-streams-service
    ports:
      - "5012:5012"
      - "8187:8187"
    volumes:
      - "./docker-logs:/workspace/kafka-streams-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5012 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=error"
      - "LOGGING_LEVEL_ROOT=error"
      - "SERVER_PORT=8187"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/certs"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "LOG_APP-NAME=kafka-streams-service"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  analytics-service:
    image: ${GROUP_ID}/analytics.service:${SERVICE_VERSION:-latest}
    container_name: analytics-service
    ports:
      - "5013:5013"
      - "8188:8188"
    volumes:
      - "./docker-logs:/workspace/analytics-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8188"
      - "SERVER_SERVLET_CONTEXT-PATH=/"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm"
      - "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak-authorization-server:9091/auth/realms/microservices-realm/protocol/openid-connect/certs"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=analytics&binaryTransfer=true&reWriteBatchedInserts=true"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "LOG_APP-NAME=analytics-service"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  discovery-service-1:
    image: ${GROUP_ID}/discovery.service:${SERVICE_VERSION:-latest}
    container_name: discovery-service-1
    ports:
      - "5014:5014"
      - "8761:8761"
    volumes:
      - "./docker-logs:/workspace/discovery-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5014 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8761"
      - "SPRING_PROFILES_ACTIVE=peer1"
      - "EUREKA_INSTANCE_HOSTNAME=discovery-service-1"
      - "LOG_APP-NAME=discovery-service-1"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  discovery-service-2:
    image: ${GROUP_ID}/discovery.service:${SERVICE_VERSION:-latest}
    container_name: discovery-service-2
    ports:
      - "5015:5015"
      - "8762:8762"
    volumes:
      - "./docker-logs:/workspace/discovery-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5015 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_ROOT=info"
      - "SERVER_PORT=8762"
      - "SPRING_PROFILES_ACTIVE=peer2"
      - "EUREKA_INSTANCE_HOSTNAME=discovery-service-2"
      - "LOG_APP-NAME=discovery-service-2"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  gateway-service-1:
    image: ${GROUP_ID}/gateway.service:${SERVICE_VERSION:-latest}
    container_name: gateway-service-1
    ports:
      - "5016:5016"
      - "9094:9094"
    volumes:
      - "./docker-logs:/workspace/gateway-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    links:
      - "redis-master"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5016 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=debug"
      - "LOGGING_LEVEL_ROOT=debug"
      - "SERVER_PORT=9094"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_REDIS_HOST=redis"
      - "LOG_APP-NAME=gateway-service-1"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}

  gateway-service-2:
    image: ${GROUP_ID}/gateway.service:${SERVICE_VERSION:-latest}
    container_name: gateway-service-2
    ports:
      - "5017:5017"
      - "9093:9093"
    volumes:
      - "./docker-logs:/workspace/gateway-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
      - "./check-keycloak-server-started.sh:/usr/local/bin/check-keycloak-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    links:
      - "redis-master"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5017 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=debug"
      - "LOGGING_LEVEL_ROOT=debug"
      - "SERVER_PORT=9093"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888,http://config-server-ha:8889"
      - "SPRING_REDIS_HOST=redis"
      - "LOG_APP-NAME=gateway-service-2"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/"
      - "ENCRYPT_KEY=${ENCRYPT_KEY}"
      - "SPRING_ZIPKIN_SENDER_TYPE=kafka"
      - "SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092"
      - "SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0"
      - "MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411"
    networks:
      - ${GLOBAL_NETWORK:-services}
